model_type: "med3d"        # or "monai", "resnet"
model_depth: 10
freeze_backbone: true
shortcut_type: "B"
early_stopping_patience: 20

batch_size: 32
max_epochs: 70
lr: 0.001
weight_decay: 0.01
balancer_type: "proportional"
main_classes: True


scheduler:
  type: "StepLR"
  step_size: 10
  gamma: 0.5

