site_name: Vertebrae Classifier
theme:
  name: "material"
  palette:
    - scheme: default
      primary: indygo
      toggle:
        icon: material/weather-night
        name: Tryb ciemny
    - scheme: slate
      primary: indygo
      toggle:
        icon: material/weather-sunny
        name: Tryb jasny
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            merge_init_into_class: true
            group_by_category: true     
            show_source: true
            members_order: source
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands: commands.md
  - Code Docs:
      - Data preparation: code/data_preparation.md
      - Training: code/training.md
      - Modeling: code/modeling.md
      - Inference: code/inference.md
site_author: Mateusz Ostaszewski
